# Generated by Django 5.2 on 2025-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('yop', models.IntegerField(verbose_name='Year of Passing')),
                ('tenth_percent', models.FloatField(verbose_name='10th Percentage')),
                ('twelfth_percent', models.FloatField(verbose_name='12th Percentage')),
                ('degree_percent', models.FloatField(verbose_name='Degree Percentage')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('type_of_data', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='student_dat_name_b06731_idx'), models.Index(fields=['gender'], name='student_dat_gender_d6e048_idx'), models.Index(fields=['degree'], name='student_dat_degree_17bc70_idx')],
            },
        ),
    ]
