# Generated by Django 5.2 on 2025-04-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.requirement')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.subject')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='subjects',
            field=models.ManyToManyField(through='student_data.RequirementSubject', to='student_data.subject'),
        ),
    ]
