# Generated by Django 5.2 on 2025-04-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_requirementsubject_requirement_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsubject',
            name='degree_percent_cutoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementsubject',
            name='tenth_percent_cutoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementsubject',
            name='twelfth_percent_cutoff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
