# Generated by Django 5.2 on 2025-04-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_requirementsubject_degree_percent_cutoff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementsubject',
            name='degree_percent_cutoff',
        ),
        migrations.RemoveField(
            model_name='requirementsubject',
            name='tenth_percent_cutoff',
        ),
        migrations.RemoveField(
            model_name='requirementsubject',
            name='twelfth_percent_cutoff',
        ),
    ]
