# Generated by Django 5.2 on 2025-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0004_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scheduled_requirements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_requirements',
        ),
        migrations.AddField(
            model_name='requirement',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
