# Generated by Django 5.2 on 2025-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0005_remove_student_scheduled_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scheduled_requirements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_requirements',
            field=models.IntegerField(default=0),
        ),
    ]
