# Generated by Django 5.2 on 2025-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0006_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='percentage_10th',
            field=models.FloatField(blank=True, null=True, verbose_name='10th Percentage Criteria'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='percentage_12th',
            field=models.FloatField(blank=True, null=True, verbose_name='12th Percentage Criteria'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='percentage_degree',
            field=models.FloatField(blank=True, null=True, verbose_name='Degree Percentage Criteria'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='percentage_master',
            field=models.FloatField(blank=True, null=True, verbose_name="Master's Percentage Criteria"),
        ),
    ]
