# Generated by Django 5.2 on 2025-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0006_student_scheduled_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='company_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
