# Generated by Django 5.2 on 2025-04-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0007_alter_requirement_company_code'),
    ]

    operations = [
    ]
