# Generated by Django 5.2 on 2025-04-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0009_remove_requirementstudent_student_dat_status_c1a160_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementstudent',
            name='student_status',
        ),
        migrations.AddField(
            model_name='requirementstudent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='requirementstudent',
            index=models.Index(fields=['status'], name='student_dat_status_c1a160_idx'),
        ),
    ]
