# Generated by Django 5.2 on 2025-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0010_remove_requirementstudent_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('not_cleared', 'Not Cleared'), ('cleared', 'Cleared'), ('partially_cleared', 'Partially Cleared')], default='not_cleared', help_text='Overall clearance status of all requirements', max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='student_dat_status_246ea7_idx'),
        ),
    ]
