# Generated by Django 5.2 on 2025-04-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0011_student_status_student_student_dat_status_246ea7_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='student_dat_status_246ea7_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
