# Generated by Django 5.2 on 2025-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0012_remove_student_student_dat_status_246ea7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
