# Generated by Django 5.2 on 2025-04-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0013_student_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_paid',
        ),
    ]
