# Generated by Django 5.2 on 2025-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0014_remove_student_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_placed',
            field=models.BooleanField(default=False, verbose_name='Placed Status'),
        ),
    ]
