# Generated by Django 5.2 on 2025-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0015_student_is_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementstudent',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Interview Feedback/Status'),
        ),
    ]
