# Generated by Django 5.2 on 2025-04-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0016_requirementstudent_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='escalation',
            field=models.TextField(blank=True, help_text='Details about the escalation raised', null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='escalation_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
