# Generated by Django 5.2 on 2025-04-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0017_requirement_escalation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('result', models.CharField(choices=[('pending', 'Result Pending'), ('selected', 'Got Selects'), ('no_selects', 'No Selects'), ('partial_selects', 'Partial Selects'), ('cancelled', 'Drive Cancelled'), ('postponed', 'Drive Postponed')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_details', to='student_data.requirement')),
                ('students_appeared', models.ManyToManyField(blank=True, to='student_data.student')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
