# Generated by Django 5.2 on 2025-04-25 03:22

from datetime import timezone
from django.db import migrations

def migrate_old_requirements(apps, schema_editor):
    Requirement = apps.get_model('student_data', 'Requirement')
    ScheduledRequirement = apps.get_model('student_data', 'ScheduledRequirement')
    
    # Get all scheduled requirements without a linked ScheduledRequirement
    requirements = Requirement.objects.filter(is_scheduled=True)
    
    for req in requirements:
        if not hasattr(req, 'scheduled_details'):  # Check if already exists
            ScheduledRequirement.objects.create(
                requirement=req,
                scheduled_date=req.schedule_date or timezone.now().date(),  # Fallback to today
                result='pending',  # Default status
                feedback="",  # Empty feedback
            )

def reverse_migration(apps, schema_editor):
    # Optional: Define how to reverse this migration (delete ScheduledRequirement entries)
    ScheduledRequirement = apps.get_model('student_data', 'ScheduledRequirement')
    ScheduledRequirement.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0018_scheduledrequirement'),
    ]
    
    operations = [
        migrations.RunPython(migrate_old_requirements, reverse_migration),
    ]


